= Modo BE API Docs
Powered By Dongwhwan Lee, https://github.com/hwanld
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 1
:sectlinks:

[[Books-save]]
== Books-save

* Books에 join되어있는 여러 개의 pictures를 한 번에 업로드 하기 위해서, `Books-save` 메소드 하나로 `Pictures 저장` 및 `Books-Pictures 조인` 까지 한 번에 처리합니다.
* 아래 HTTP Request에 있는 Body는 PicturesSaveRequestDto로, 해당 Dto의 picturesSaveRequestDtoList는 각각의 사진을 DB에 저장하기 위한 picturesSaveRequestDto 의 List 형태로 이루어져 있습니다.

operation::Books-save[snippets='http-request,request-headers,request-fields,http-response,response-fields']

[[Books-createPreUrl]]
== Books-createPreUrl

* Books Upload 시에 사진을 업로드 하기 위한 preSignedURL을 AWS S3로부터 발급받기 위한 API입니다.
* keyName으로 URL에 식별자를 주면 해당 식별자를 사용해서 preSignedURL을 발급합니다. keyName은 Upload하는 파일의 이름과는 무관합니다.
* 생성된 이미지의 URL은 https://modo-deploy.s3.ap-northeast-2.amazonaws.com/{파일명} 을 따릅니다.

operation::Books-createPreUrl[snippets='http-request,request-headers,query-parameters,http-response']

[[Books-update]]
== Books-update

operation::Books-update[snippets='http-request,request-headers,request-fields,http-response,response-fields']

[[Books-delete]]
== Books-delete

operation::Books-delete[snippets='http-request,request-headers,query-parameters,http-response']

[[Books-getBooksList]]
== Books-getBooksList

* 메인 페이지 처음 로드 시 아무런 검색어 없이 책 리스트를 조회하는 API 입니다.
* 요청을 보낸 사용자의 등록된 위치를 기준으로 가까운 순서대로 정렬해서 리턴합니다.
* 해당 API를 호출하기 위해선 searchingWord queryParameter를 "" empty string으로 보내주셔야 합니다.

operation::Books-getBooksList[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

[[Books-getBooksList_WithSearching]]
== Books-getBooksList_WithSearching

* 특정 문자열을 포함한 검색 결과 책 리스트를 조회하는 API 입니다.
* 기존 프론트엔드의 요청에 따라 위의 getBooksList와 엔드포인트가 같습니다.
* 요청을 보낸 사용자의 등록된 위치를 기준으로 가까운 순서대로 정렬해서 리턴합니다.
* 검색한 문자열이 책 제목에 포함되어 있지 않은 경우에는 검색 결과에서 무조건 제외됩니다.

operation::Books-getBooksListWithSearching[snippets='http-request,request-headers,query-parameters,http-response,response-fields']

[[Books-findBooks]]
== Books-findBooks

* 책 리스트 (페이지네이션) 조회 이후 상세 조회 시 사용되는 API입니다.

operation::Books-findBooks[snippets='http-request,request-headers,query-parameters,http-response,response-fields']