= Modo BE API Docs
Powered By Dongwhwan Lee, https://github.com/hwanld
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 1
:sectlinks:

[[Users-save]]
== Users-save
* 소셜 로그인 통합으로 인해서 실 사용하지는 않는 메소드 입니다.

operation::Users-save[snippets='http-request,request-fields,http-response,response-fields']

[[Users-findUsers]]
== Users-findUsers

operation::Users-findUsers[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

[[Users-findUsersFetchReview]]
== Users-findUsersFetchReview

operation::Users-findUsersFetchReview[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

[[Users-addReview]]
== Users-addReview

operation::Users-addReview[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

[[Users-changeNickname]]
== Users-changeNickname

operation::Users-changeNickname[snippets='http-request,request-headers,path-parameters,http-response,response-fields']

[[Users-changeLocation]]
== Users-changeLocation

operation::Users-changeLocation[snippets='http-request,request-headers,path-parameters,http-response,response-fields']