= Modo BE API Docs
Powered By Dongwhwan Lee, https://github.com/hwanld
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 1
:sectlinks:

[[Users-save]]
== Users-save

operation::Users-save[snippets='http-request,request-fields,http-response,response-fields']

[[Users-findUsers]]
== Users-findUsers

operation::Users-findUsers[snippets='http-request,path-parameters,http-response,response-fields']

[[Users-findUsersFetchReview]]
== Users-findUsersFetchReview

operation::Users-findUsersFetchReview[snippets='http-request,path-parameters,http-response,response-fields']

[[Users-addReview]]
== Users-addReview

operation::Users-addReview[snippets='http-request,path-parameters,http-response,response-fields']

[[Users-changeNickname]]
== Users-changeNickname

operation::Users-changeNickname[snippets='http-request,path-parameters,http-response,response-fields']

[[Users-changeLocation]]
== Users-changeLocation

operation::Users-changeLocation[snippets='http-request,path-parameters,http-response,response-fields']