# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Redis Server in GitHub Actions
        uses: supercharge/redis-github-action@1.5.0

      - name: Create Properties files
        run: touch ./src/main/resources/application.properties ; touch ./src/main/resources/application-real1.properties ; touch ./src/main/resources/application-real2.properties

      - name: Load Application Properties
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.properties

      - name: Load Application Real1 Properties
        run: echo "${{ secrets.APPLICATION_REAL1_PROPERTIES }}" > ./src/main/resources/application-real1.properties

      - name: Load Application Real2 Properties
        run: echo "${{ secrets.APPLICATION_REAL2_PROPERTIES }}" > ./src/main/resources/application-real2.properties

      - name: Build with gradle
        run: ./gradlew clean build

      - name: Build with gradle
        run: ./gradlew clean build

      - name: Build Docker image
        run: docker build -t wkazxf/modo .

      - name: Login Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker Hub
        run: docker push wkazxf/modo





